import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1766696011515 implements MigrationInterface {
    name = 'InitialSchema1766696011515'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(320) NOT NULL, "username" character varying(100), "display_name" character varying(255) NOT NULL, "first_name" character varying(100), "last_name" character varying(100), "password_hash" character varying(255), "password_algo" character varying(20) NOT NULL DEFAULT 'argon2id', "password_changed_at" TIMESTAMP WITH TIME ZONE, "must_change_password" boolean NOT NULL DEFAULT false, "status" character varying(20) NOT NULL DEFAULT 'invited', "work_phone" character varying(50), "mobile_phone" character varying(50), "employee_id" character varying(100), "title" character varying(200), "department" character varying(200), "location" character varying(200), "cost_center" character varying(50), "manager_id" uuid, "avatar_url" character varying(500), "locale" character varying(20) NOT NULL DEFAULT 'en-US', "time_zone" character varying(50) NOT NULL DEFAULT 'America/New_York', "date_format" character varying(20) NOT NULL DEFAULT 'MM/DD/YYYY', "time_format" character varying(10) NOT NULL DEFAULT '12h', "mfa_enabled" boolean NOT NULL DEFAULT false, "mfa_secret" character varying(255), "mfa_backup_codes" jsonb, "mfa_recovery_email" character varying(320), "failed_login_attempts" integer NOT NULL DEFAULT '0', "locked_until" TIMESTAMP WITH TIME ZONE, "last_failed_login_at" TIMESTAMP WITH TIME ZONE, "email_verified" boolean NOT NULL DEFAULT false, "email_verified_at" TIMESTAMP WITH TIME ZONE, "is_admin" boolean NOT NULL DEFAULT false, "is_system_user" boolean NOT NULL DEFAULT false, "invited_by" uuid, "invited_at" TIMESTAMP WITH TIME ZONE, "activation_token" character varying(255), "activation_token_expires_at" TIMESTAMP WITH TIME ZONE, "activated_at" TIMESTAMP WITH TIME ZONE, "deactivated_at" TIMESTAMP WITH TIME ZONE, "deactivated_by" uuid, "deactivation_reason" text, "suspended_at" TIMESTAMP WITH TIME ZONE, "suspended_by" uuid, "suspension_reason" text, "suspension_expires_at" TIMESTAMP WITH TIME ZONE, "last_login_at" TIMESTAMP WITH TIME ZONE, "last_login_ip" character varying(45), "last_activity_at" TIMESTAMP WITH TIME ZONE, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1b7c676ffb354a9cabc87b7da9" ON "users" ("is_admin") `);
        await queryRunner.query(`CREATE INDEX "IDX_fba2d8e029689aa8fea98e53c9" ON "users" ("manager_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c162e1fe9d744b0721daea3b1c" ON "users" ("department") `);
        await queryRunner.query(`CREATE INDEX "IDX_3676155292d72c67cd4e090514" ON "users" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0837b566b883183034a42db0e0" ON "users" ("employee_id") WHERE "employee_id" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_01b38a262e9036dfcd0d686de6" ON "users" ("username") WHERE "username" IS NOT NULL AND "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7fdbf1baeb91b6f822b5d57e19" ON "users" ("email") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "category" character varying(100), "resource_type" character varying(100), "action_type" character varying(50), "is_system" boolean NOT NULL DEFAULT false, "is_dangerous" boolean NOT NULL DEFAULT false, "display_order" integer NOT NULL DEFAULT '0', "icon" character varying(100), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_637007c67b604bd971d4fe6823" ON "permissions" ("resource_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_aad80a27f0a425bfc3f092a732" ON "permissions" ("category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8dad765629e83229da6feda1c1" ON "permissions" ("code") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, "conditions" jsonb, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_25d24010f53bb80b78e412c9656" UNIQUE ("role_id", "permission_id"), CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, "source" character varying(50) NOT NULL DEFAULT 'direct', "source_id" uuid, "valid_from" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "valid_until" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_23ed6f04fe43066df08379fd034" UNIQUE ("user_id", "role_id"), CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_da27d912745ad6fae4eaaf07d3" ON "user_roles" ("valid_from", "valid_until") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "parent_id" uuid, "hierarchy_level" integer NOT NULL DEFAULT '0', "hierarchy_path" character varying(500), "scope" character varying(50) NOT NULL DEFAULT 'global', "max_users" integer, "weight" integer NOT NULL DEFAULT '0', "is_system" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "is_default" boolean NOT NULL DEFAULT false, "icon" character varying(100), "color" character varying(50), "metadata" jsonb NOT NULL DEFAULT '{}', "created_by" uuid, "updated_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f6d54f95c31b73fb1bdd8e91d0c" UNIQUE ("code"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9f58bffa9bdcc402c0438a60c" ON "roles" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a3edd7bc16920c3287331ea42" ON "roles" ("is_system") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e97eeaf865aeda0d20c0c5c50" ON "roles" ("parent_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f6d54f95c31b73fb1bdd8e91d0" ON "roles" ("code") `);
        await queryRunner.query(`CREATE TABLE "groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "parent_id" uuid, "hierarchy_level" integer NOT NULL DEFAULT '0', "hierarchy_path" character varying(500), "type" character varying(50) NOT NULL DEFAULT 'standard', "membership_rules" jsonb, "is_system" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "icon" character varying(100), "color" character varying(50), "metadata" jsonb NOT NULL DEFAULT '{}', "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8989cafa0945a366f0c8716e609" UNIQUE ("code"), CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ed580a627f0d82d392897b4bca" ON "groups" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b343e4f936b28da5922520105" ON "groups" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_d768ea35a407c2ba9c0b038b61" ON "groups" ("parent_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8989cafa0945a366f0c8716e60" ON "groups" ("code") `);
        await queryRunner.query(`CREATE TABLE "group_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "group_id" uuid NOT NULL, "user_id" uuid NOT NULL, "is_manager" boolean NOT NULL DEFAULT false, "valid_from" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "valid_until" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f5939ee0ad233ad35e03f5c65c1" UNIQUE ("group_id", "user_id"), CONSTRAINT "PK_86446139b2c96bfd0f3b8638852" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_20a555b299f75843aa53ff8b0e" ON "group_members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c840df5db52dc6b4a1b0b69c6" ON "group_members" ("group_id") `);
        await queryRunner.query(`CREATE TABLE "group_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "group_id" uuid NOT NULL, "role_id" uuid NOT NULL, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_31cb33278c5d3f7aed58766840a" UNIQUE ("group_id", "role_id"), CONSTRAINT "PK_c88b2351f40bf170bc7ab7e8fda" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_35d4b5f7da6e1a9a730c3621ec" ON "group_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f428ea82b51ea6c795689cdb8" ON "group_roles" ("group_id") `);
        await queryRunner.query(`CREATE TABLE "property_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "name" character varying(100) NOT NULL, "category" character varying(50) NOT NULL, "description" text, "base_type" character varying(50) NOT NULL, "default_config" jsonb NOT NULL DEFAULT '{}', "validation_rules" jsonb NOT NULL DEFAULT '{}', "default_widget" character varying(50), "icon" character varying(50), "is_system" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_1f7b17d42cf5cbd751912ddda14" UNIQUE ("code"), CONSTRAINT "PK_129390b286b9c776438dfa475a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b03cfc29a73bc8ab5edf39c826" ON "property_types" ("category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1f7b17d42cf5cbd751912ddda1" ON "property_types" ("code") `);
        await queryRunner.query(`CREATE TABLE "choice_lists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "is_system" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_931628f1c40bc1d2b193ee07560" UNIQUE ("code"), CONSTRAINT "PK_32e58b5d1206ca7bd235da92c66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_931628f1c40bc1d2b193ee0756" ON "choice_lists" ("code") `);
        await queryRunner.query(`CREATE TABLE "choice_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "choice_list_id" uuid NOT NULL, "value" character varying(255) NOT NULL, "label" character varying(255) NOT NULL, "position" integer NOT NULL DEFAULT '0', "color" character varying(50), "icon" character varying(100), "is_default" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_9d19126c923b35ffd71c6b08bbd" UNIQUE ("choice_list_id", "value"), CONSTRAINT "PK_bffbbb5b6dce82a7246514834aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_98334e02c5109bd3a8ec155c2b" ON "choice_items" ("choice_list_id") `);
        await queryRunner.query(`CREATE TABLE "property_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "collection_id" uuid NOT NULL, "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "property_type_id" uuid NOT NULL, "column_name" character varying(100) NOT NULL, "config" jsonb NOT NULL DEFAULT '{}', "is_required" boolean NOT NULL DEFAULT false, "is_unique" boolean NOT NULL DEFAULT false, "is_indexed" boolean NOT NULL DEFAULT false, "validation_rules" jsonb NOT NULL DEFAULT '{}', "default_value" text, "default_value_type" character varying(50) NOT NULL DEFAULT 'static', "position" integer NOT NULL DEFAULT '0', "is_visible" boolean NOT NULL DEFAULT true, "is_readonly" boolean NOT NULL DEFAULT false, "display_format" character varying(100), "placeholder" character varying(255), "help_text" text, "reference_collection_id" uuid, "reference_display_property" character varying(100), "reference_filter" jsonb, "choice_list_id" uuid, "owner_type" character varying(20) NOT NULL DEFAULT 'custom', "is_system" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "is_searchable" boolean NOT NULL DEFAULT false, "is_sortable" boolean NOT NULL DEFAULT true, "is_filterable" boolean NOT NULL DEFAULT true, "metadata" jsonb NOT NULL DEFAULT '{}', "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2211a0f9fca1a63a5a8ff76bda2" UNIQUE ("collection_id", "code"), CONSTRAINT "PK_09013b5e4e940a81de054ac6fd2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_16cc6ea2ff3b1429345831f1f9" ON "property_definitions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7ba7ffa905aec05e079199292" ON "property_definitions" ("reference_collection_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_10dab69d18bbe034d20839f2ad" ON "property_definitions" ("property_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e4c4613796c3af281556a2b62" ON "property_definitions" ("collection_id") `);
        await queryRunner.query(`CREATE TABLE "collection_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "plural_name" character varying(255), "description" text, "category" character varying(100), "application_id" uuid, "owner_type" character varying(20) NOT NULL DEFAULT 'custom', "table_name" character varying(100) NOT NULL, "label_property" character varying(100) NOT NULL DEFAULT 'name', "secondary_label_property" character varying(100), "is_extensible" boolean NOT NULL DEFAULT true, "is_audited" boolean NOT NULL DEFAULT true, "enable_versioning" boolean NOT NULL DEFAULT false, "enable_attachments" boolean NOT NULL DEFAULT true, "enable_activity_log" boolean NOT NULL DEFAULT true, "enable_search" boolean NOT NULL DEFAULT true, "is_system" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "icon" character varying(100), "color" character varying(50), "default_access" character varying(20) NOT NULL DEFAULT 'read', "metadata" jsonb NOT NULL DEFAULT '{}', "created_by" uuid, "updated_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d74cad0dd7ab2f1144e34e1a816" UNIQUE ("code"), CONSTRAINT "UQ_7c22e7ac994b29b2d8320bf3bcf" UNIQUE ("table_name"), CONSTRAINT "PK_92ac9ed8fcf26e5f49e30a29c2a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e317662a80e3314c64265c35e9" ON "collection_definitions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_d24aec9ddb25523068aefad8c5" ON "collection_definitions" ("application_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d816b7a55d18d87ca3b6065a49" ON "collection_definitions" ("category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7c22e7ac994b29b2d8320bf3bc" ON "collection_definitions" ("table_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d74cad0dd7ab2f1144e34e1a81" ON "collection_definitions" ("code") `);
        await queryRunner.query(`CREATE TABLE "collection_access_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "collection_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "role_id" uuid, "group_id" uuid, "user_id" uuid, "can_read" boolean NOT NULL DEFAULT false, "can_create" boolean NOT NULL DEFAULT false, "can_update" boolean NOT NULL DEFAULT false, "can_delete" boolean NOT NULL DEFAULT false, "conditions" jsonb, "priority" integer NOT NULL DEFAULT '100', "is_active" boolean NOT NULL DEFAULT true, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_685125fdb89c2749d2c76bca5a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_52174f0e91e1a5a0c87c9fcf78" ON "collection_access_rules" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_2bbd90ecb185529732938857fa" ON "collection_access_rules" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d9437ad9cb5e4aedaf442b949e" ON "collection_access_rules" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ee922b564bc954b4d97eae815" ON "collection_access_rules" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0644be2a2e4d4a95dae2039d04" ON "collection_access_rules" ("collection_id") `);
        await queryRunner.query(`CREATE TABLE "property_access_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "property_id" uuid NOT NULL, "role_id" uuid, "group_id" uuid, "user_id" uuid, "can_read" boolean NOT NULL DEFAULT true, "can_write" boolean NOT NULL DEFAULT true, "conditions" jsonb, "priority" integer NOT NULL DEFAULT '100', "is_active" boolean NOT NULL DEFAULT true, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_64e3b9fa96a1735ba4741905d88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c5f3ff32b318d551d8f4a7b28" ON "property_access_rules" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0b9e97943e753481035a49922" ON "property_access_rules" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0189d2c9de5f8ef47506294a27" ON "property_access_rules" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_314d7767bd038e2d47aebb208f" ON "property_access_rules" ("property_id") `);
        await queryRunner.query(`CREATE TABLE "user_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "session_token" character varying(500) NOT NULL, "refresh_token" character varying(500), "device_id" character varying(255), "device_name" character varying(255), "device_type" character varying(50), "user_agent" text, "ip_address" character varying(45), "geo_location" jsonb, "is_active" boolean NOT NULL DEFAULT true, "is_remembered" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "last_activity_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, "revoked_reason" character varying(100), CONSTRAINT "UQ_e5eb7a3c7766f941fe16b9edecb" UNIQUE ("session_token"), CONSTRAINT "PK_e93e031a5fed190d4789b6bfd83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0c30b2278a5d31e23fcaee4887" ON "user_sessions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_dbc81ff542b1b3366bae195f2a" ON "user_sessions" ("expires_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e5eb7a3c7766f941fe16b9edec" ON "user_sessions" ("session_token") `);
        await queryRunner.query(`CREATE INDEX "IDX_e9658e959c490b0a634dfc5478" ON "user_sessions" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "access_conditions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rule_id" uuid NOT NULL, "field" character varying NOT NULL, "operator" character varying NOT NULL, "value" character varying NOT NULL, CONSTRAINT "PK_dc7b7cc80c74b4cb2c2c908bc8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "access_condition_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rule_id" uuid NOT NULL, "logic" character varying NOT NULL, CONSTRAINT "PK_a08fcc4ccef7a20eb06585d161d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auth_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "password_min_length" integer NOT NULL DEFAULT '12', "password_require_uppercase" boolean NOT NULL DEFAULT true, "password_require_lowercase" boolean NOT NULL DEFAULT true, "password_require_numbers" boolean NOT NULL DEFAULT true, "password_require_symbols" boolean NOT NULL DEFAULT true, "password_history_count" integer NOT NULL DEFAULT '12', "password_expiry_days" integer NOT NULL DEFAULT '90', "password_block_common" boolean NOT NULL DEFAULT true, "max_failed_attempts" integer NOT NULL DEFAULT '5', "lockout_duration_minutes" integer NOT NULL DEFAULT '30', "session_timeout_minutes" integer NOT NULL DEFAULT '480', "max_concurrent_sessions" integer NOT NULL DEFAULT '5', "remember_me_duration_days" integer NOT NULL DEFAULT '30', "mfa_required" boolean NOT NULL DEFAULT false, "mfa_grace_period_days" integer NOT NULL DEFAULT '7', "sso_enabled" boolean NOT NULL DEFAULT false, "sso_enforce" boolean NOT NULL DEFAULT false, "sso_config" jsonb, "ip_whitelist_enabled" boolean NOT NULL DEFAULT false, "ip_whitelist" jsonb NOT NULL DEFAULT '[]', "allowed_auth_methods" jsonb NOT NULL DEFAULT '["password", "sso", "ldap"]', "allow_password_reset" boolean NOT NULL DEFAULT true, "allow_profile_edit" boolean NOT NULL DEFAULT true, "allow_mfa_self_enrollment" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_daf9fe3ab40a3241250fcd21127" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auth_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "event_type" character varying(50) NOT NULL, "success" boolean NOT NULL, "ip_address" character varying(45), "user_agent" text, "geo_location" jsonb, "details" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ab929cc6084ffb3fd795bd983c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_64ac9bded13b2b6b75b128d8e5" ON "auth_events" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_aff0693e5ee9e891fcdb414daa" ON "auth_events" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_d27703f0a3d79ba424741807cb" ON "auth_events" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "collection_code" character varying(100), "record_id" uuid, "action" character varying(50) NOT NULL, "old_values" jsonb, "new_values" jsonb, "ip_address" character varying(45), "user_agent" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0acee5e593954a1dc4ac8aad3" ON "audit_logs" ("record_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0bacca40d90fcebfc311982eb1" ON "audit_logs" ("collection_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "nav_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "scope" character varying(50) NOT NULL DEFAULT 'role', "role_id" uuid, "group_id" uuid, "user_id" uuid, "priority" integer NOT NULL DEFAULT '100', "is_default" boolean NOT NULL DEFAULT false, "is_system" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_92556f552f70c0531bdf4fc9d85" UNIQUE ("code"), CONSTRAINT "PK_eab82f3592b4f3bdfa425eb651a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_296ff17c5fdac130091f783281" ON "nav_profiles" ("is_default") `);
        await queryRunner.query(`CREATE INDEX "IDX_4db63a99d84dfd65fe3dca1bb2" ON "nav_profiles" ("scope") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_92556f552f70c0531bdf4fc9d8" ON "nav_profiles" ("code") `);
        await queryRunner.query(`CREATE TABLE "nav_profile_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "profile_id" uuid NOT NULL, "type" character varying(50) NOT NULL, "code" character varying(100) NOT NULL, "label" character varying(255) NOT NULL, "icon" character varying(100), "route" character varying(500), "external_url" character varying(500), "parent_id" uuid, "position" integer NOT NULL DEFAULT '0', "visibility_expression" text, "required_permission" character varying(100), "is_visible" boolean NOT NULL DEFAULT true, "is_expanded" boolean NOT NULL DEFAULT false, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cb0391e27b4c5bfa13728f5ebf4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e61477461f4ab1ba6729234fe4" ON "nav_profile_items" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f02d51b25f5821bc1ee6780cc1" ON "nav_profile_items" ("profile_id") `);
        await queryRunner.query(`CREATE TABLE "instance_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category" character varying(100) NOT NULL, "key" character varying(100) NOT NULL, "value" jsonb NOT NULL, "description" text, "is_system" boolean NOT NULL DEFAULT false, "updated_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f4841fbd4c9819d5ade4b5dfeb8" UNIQUE ("key"), CONSTRAINT "PK_eb2567a5e4188cd54689e1d79ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f4841fbd4c9819d5ade4b5dfeb" ON "instance_settings" ("key") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c03e48624b266373a313f87d4" ON "instance_settings" ("category") `);
        await queryRunner.query(`CREATE TABLE "password_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "minLength" integer NOT NULL DEFAULT '8', "requireUppercase" boolean NOT NULL DEFAULT false, "requireLowercase" boolean NOT NULL DEFAULT false, "requireNumbers" boolean NOT NULL DEFAULT false, "requireSpecialChars" boolean NOT NULL DEFAULT false, "expirationDays" integer NOT NULL DEFAULT '90', "historyCount" integer NOT NULL DEFAULT '5', "maxAttempts" integer NOT NULL DEFAULT '3', "lockoutMinutes" integer NOT NULL DEFAULT '30', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5468b65a86afc8563ac81cb9153" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ldap_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "host" character varying NOT NULL, "port" integer NOT NULL DEFAULT '389', "secure" boolean NOT NULL DEFAULT false, "bindDn" character varying, "bindPassword" character varying, "searchBase" character varying NOT NULL, "userSearchFilter" character varying NOT NULL, "usernameAttribute" character varying NOT NULL DEFAULT 'uid', "emailAttribute" character varying NOT NULL DEFAULT 'mail', "fullNameAttribute" character varying NOT NULL DEFAULT 'cn', "enabled" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_617b64e3f20ff5598a11ea7661e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sso_providers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "type" character varying NOT NULL, "issuer" character varying, "client_id" character varying, "client_secret" character varying, "authorization_url" character varying, "token_url" character varying, "user_info_url" character varying, "jwks_url" character varying, "scopes" character varying, "entity_id" character varying, "sso_url" character varying, "slo_url" character varying, "certificate" text, "jit_enabled" boolean NOT NULL DEFAULT false, "jit_default_roles" jsonb, "jit_group_mapping" jsonb, "jit_update_profile" boolean NOT NULL DEFAULT true, "attribute_mapping" jsonb, "button_text" character varying, "button_icon_url" character varying, "display_order" integer NOT NULL DEFAULT '0', "allowed_domains" jsonb, "logout_redirect_url" character varying, "enabled" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_85208f3eacf568550f725f5097a" UNIQUE ("slug"), CONSTRAINT "PK_348feeee9ed68f9161a2f5ffeb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "instance_customizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "configType" character varying NOT NULL, "resourceKey" character varying NOT NULL, "value" jsonb, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, CONSTRAINT "PK_0e3a98ce06a5841f18b951012ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "config_change_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "configType" character varying NOT NULL, "code" character varying, "changeType" character varying NOT NULL, "details" jsonb, "userId" character varying, "changedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1be86c25d2fc54beef9398c6991" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "password_hash" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_da65ed4600e5e6bc9315754a8b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4933dc7a01356ac0733a5ad52d" ON "password_history" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token" character varying(255) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_ab673f0e63eac966762155508ee" UNIQUE ("token"), CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7c038e5a589b06cbe4320cc88b" ON "password_reset_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ab673f0e63eac966762155508e" ON "password_reset_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_52ac39dd8a28730c63aeb428c9" ON "password_reset_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "email_verification_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "email" character varying(320) NOT NULL, "token" character varying(255) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "verified_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_3d1613f95c6a564a3b588d161ae" UNIQUE ("token"), CONSTRAINT "PK_417a095bbed21c2369a6a01ab9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b7c64ecae33a54d3a11a4e6b6e" ON "email_verification_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3d1613f95c6a564a3b588d161a" ON "email_verification_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_fdcb77f72f529bf65c95d72a14" ON "email_verification_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token" character varying(500) NOT NULL, "family" character varying(100), "device_id" character varying(255), "ip_address" character varying(45), "user_agent" text, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "is_revoked" boolean NOT NULL DEFAULT false, "revoked_at" TIMESTAMP WITH TIME ZONE, "revoked_reason" character varying(100), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_4542dd2f38a61354a040ba9fd57" UNIQUE ("token"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3a5f57e17354e7407757e8793b" ON "refresh_tokens" ("is_revoked") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba3bd69c8ad1e799c0256e9e50" ON "refresh_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4542dd2f38a61354a040ba9fd5" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "key_hash" character varying(255) NOT NULL, "key_prefix" character varying(20) NOT NULL, "scopes" jsonb NOT NULL DEFAULT '[]', "ip_whitelist" jsonb, "expires_at" TIMESTAMP WITH TIME ZONE, "last_used_at" TIMESTAMP WITH TIME ZONE, "last_used_ip" character varying(45), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_57384430aa1959f4578046c9b81" UNIQUE ("key_hash"), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_138cc6196c7bfa61d31412aea7" ON "api_keys" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_57384430aa1959f4578046c9b8" ON "api_keys" ("key_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3baee01d8408cd3c0f89a9a97" ON "api_keys" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "user_invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(320) NOT NULL, "token" character varying(255) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "role_ids" jsonb NOT NULL DEFAULT '[]', "group_ids" jsonb NOT NULL DEFAULT '[]', "message" text, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "accepted_at" TIMESTAMP WITH TIME ZONE, "created_user_id" uuid, "invited_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_1c885f83eb2a34fedd887e43e82" UNIQUE ("token"), CONSTRAINT "PK_c8005acb91c3ce9a7ae581eca8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9f3ae879cf24686834c974effd" ON "user_invitations" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_245772caab09e629f6e80aaaba" ON "user_invitations" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1c885f83eb2a34fedd887e43e8" ON "user_invitations" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_d818b0ebcc97ef5dfb67fb7867" ON "user_invitations" ("email") `);
        await queryRunner.query(`CREATE TABLE "mfa_methods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" character varying(50) NOT NULL, "secret" text, "recovery_codes" text, "enabled" boolean NOT NULL DEFAULT false, "verified" boolean NOT NULL DEFAULT false, "last_used_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_60e4d183e6dbd427aa5549da581" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1d590a89ba342ab3515e64f6d2" ON "mfa_methods" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "theme_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "config" jsonb NOT NULL DEFAULT '{}', "theme_type" character varying NOT NULL DEFAULT 'custom', "contrast_level" character varying NOT NULL DEFAULT 'normal', "color_scheme" character varying NOT NULL DEFAULT 'dark', "is_default" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "is_deletable" boolean NOT NULL DEFAULT true, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7acdb47306e9b04ff598ca67a8d" UNIQUE ("code"), CONSTRAINT "PK_e9340ba17d97c17056d05759136" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05cbb2665b2c235e3c06f0e55b" ON "theme_definitions" ("color_scheme") `);
        await queryRunner.query(`CREATE INDEX "IDX_c8553e254fab743a15789c9367" ON "theme_definitions" ("theme_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0a7ca386aca61a735377afe1d" ON "theme_definitions" ("is_default") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7acdb47306e9b04ff598ca67a8" ON "theme_definitions" ("code") `);
        await queryRunner.query(`CREATE TABLE "user_theme_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "theme_id" uuid, "custom_overrides" jsonb NOT NULL DEFAULT '{}', "color_scheme" character varying NOT NULL DEFAULT 'auto', "auto_dark_mode" boolean NOT NULL DEFAULT true, "respect_reduced_motion" boolean NOT NULL DEFAULT true, "preference_source" character varying NOT NULL DEFAULT 'manual', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d2925210c600e2673134dcf7e8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ae77cd7cd68614f5880e102757" ON "user_theme_preferences" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "instance_branding" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "default_theme_id" uuid, "theme_overrides" jsonb NOT NULL DEFAULT '{}', "logo_url" character varying(500), "logo_dark_url" character varying(500), "favicon_url" character varying(500), "primary_color" character varying(7), "accent_color" character varying(7), "custom_css" text, "allow_user_customization" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ffa3a5f407b63635e6c7ec5e421" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "density_mode" character varying(20) NOT NULL DEFAULT 'comfortable', "sidebar_position" character varying(10) NOT NULL DEFAULT 'left', "sidebar_collapsed" boolean NOT NULL DEFAULT false, "sidebar_width" integer NOT NULL DEFAULT '260', "show_breadcrumbs" boolean NOT NULL DEFAULT true, "show_footer" boolean NOT NULL DEFAULT true, "content_width" character varying(20) NOT NULL DEFAULT 'full', "pinned_navigation" jsonb NOT NULL DEFAULT '[]', "recent_items_count" integer NOT NULL DEFAULT '5', "show_favorites_in_sidebar" boolean NOT NULL DEFAULT true, "show_recent_in_sidebar" boolean NOT NULL DEFAULT true, "language" character varying(10) NOT NULL DEFAULT 'en', "timezone" character varying(50), "date_format" character varying(20) NOT NULL DEFAULT 'MM/DD/YYYY', "time_format" character varying(5) NOT NULL DEFAULT '12h', "start_of_week" character varying(10) NOT NULL DEFAULT 'sunday', "number_format" character varying(20) NOT NULL DEFAULT 'en-US', "notification_preferences" jsonb NOT NULL DEFAULT '{"email":{"enabled":true,"frequency":"daily","categories":[]},"inApp":{"enabled":true,"sound":true,"showPreview":true},"push":{"enabled":false}}', "accessibility" jsonb NOT NULL DEFAULT '{"reduceMotion":false,"highContrast":false,"largeText":false,"screenReaderOptimized":false,"keyboardNavigation":true,"focusIndicators":true}', "keyboard_shortcuts_enabled" boolean NOT NULL DEFAULT true, "custom_shortcuts" jsonb NOT NULL DEFAULT '[]', "table_preferences" jsonb NOT NULL DEFAULT '{"defaultPageSize":25,"showRowNumbers":false,"enableColumnReorder":true,"stickyHeader":true,"alternateRowColors":false,"compactMode":false}', "dashboard_preferences" jsonb NOT NULL DEFAULT '{"autoRefreshInterval":0,"showWelcomeWidget":true}', "auto_save_enabled" boolean NOT NULL DEFAULT true, "auto_save_interval" integer NOT NULL DEFAULT '30', "confirm_before_leave" boolean NOT NULL DEFAULT true, "show_field_descriptions" boolean NOT NULL DEFAULT true, "search_include_archived" boolean NOT NULL DEFAULT false, "search_results_per_page" integer NOT NULL DEFAULT '20', "search_highlight_matches" boolean NOT NULL DEFAULT true, "home_page" character varying(255), "startup_page" character varying(255), "ava_enabled" boolean NOT NULL DEFAULT true, "ava_auto_suggest" boolean NOT NULL DEFAULT true, "ava_voice_enabled" boolean NOT NULL DEFAULT false, "sync_enabled" boolean NOT NULL DEFAULT true, "last_sync_device" character varying(255), "last_synced_at" TIMESTAMP WITH TIME ZONE, "preference_version" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e8cfb5b31af61cd363a6b6d7c25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_458057fa75b66e68a275647da2" ON "user_preferences" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "modules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "slug" character varying, "label" character varying NOT NULL, "icon" character varying, "sort_order" integer NOT NULL DEFAULT '0', "type" character varying NOT NULL DEFAULT 'list', "route" character varying, "target_config" jsonb, "application_key" character varying, "is_active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a57f2b3bd9ebb022212e634f601" UNIQUE ("key"), CONSTRAINT "PK_7dbefd488bd96c5bf31f0ce0c95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a57f2b3bd9ebb022212e634f60" ON "modules" ("key") `);
        await queryRunner.query(`CREATE TABLE "module_security" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "module_id" uuid NOT NULL, "role_id" uuid NOT NULL, "canView" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_4e41b3d2d49a520286fb067bffc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "form_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "collection_id" uuid NOT NULL, "isDefault" boolean NOT NULL DEFAULT false, "layout" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e7b46c89a49ab24f30618b410d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_111982cc806d8c26c9c445ece7" ON "form_definitions" ("collection_id") `);
        await queryRunner.query(`CREATE TABLE "form_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "form_id" uuid NOT NULL, "version" integer NOT NULL, "layout" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_46dbd35ef6adf11a8684deae1b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "access_rule_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rule_id" uuid NOT NULL, "action" character varying NOT NULL, "changes" jsonb, "performed_by" uuid NOT NULL, "performedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eabc37285db4504f74492eb2757" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "access_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "resource" character varying NOT NULL, "action" character varying NOT NULL, "decision" character varying NOT NULL, "context" jsonb, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_92362eda47f20e6eff693801adc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "property_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "property_id" uuid NOT NULL, "record_id" uuid NOT NULL, "oldValue" text, "newValue" text, "changed_by" uuid NOT NULL, "changedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3878feaf1d72785e4c4fa1d6c53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ava_audit_trail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "user_name" character varying, "user_role" character varying, "conversation_id" uuid, "user_message" text, "ava_response" text, "action_type" character varying(50) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "action_label" character varying, "action_target" character varying, "target_collection" character varying, "target_record_id" uuid, "target_display_value" character varying, "before_data" jsonb, "after_data" jsonb, "action_params" jsonb, "is_revertible" boolean NOT NULL DEFAULT false, "ip_address" character varying, "user_agent" text, "session_id" uuid, "error_message" text, "error_code" character varying, "duration_ms" integer, "completed_at" TIMESTAMP WITH TIME ZONE, "reverted_at" TIMESTAMP WITH TIME ZONE, "reverted_by" uuid, "revert_reason" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8883aeb20729f23f84dddd4cd2b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f57eac7ca7c67e6dc24f2f1be1" ON "ava_audit_trail" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_106f148639500d8a937386b5a7" ON "ava_audit_trail" ("target_collection") `);
        await queryRunner.query(`CREATE INDEX "IDX_a388db879a8dcc4ccdb37264fa" ON "ava_audit_trail" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_97c0f7d7333849f12e42cf7779" ON "ava_audit_trail" ("action_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1702c609e880eb3d176d060ed" ON "ava_audit_trail" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "ava_permission_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "collection_code" character varying, "action_type" character varying(50) NOT NULL, "is_enabled" boolean NOT NULL DEFAULT true, "requires_confirmation" boolean NOT NULL DEFAULT true, "allowed_roles" jsonb NOT NULL DEFAULT '[]', "excluded_roles" jsonb NOT NULL DEFAULT '[]', "created_by" uuid, "updated_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_11683766f65091641045f8ae30f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6cd7923ae0d32881a0d82c0280" ON "ava_permission_configs" ("collection_code", "action_type") `);
        await queryRunner.query(`CREATE TABLE "ava_global_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ava_enabled" boolean NOT NULL DEFAULT true, "read_only_mode" boolean NOT NULL DEFAULT false, "allow_create_actions" boolean NOT NULL DEFAULT true, "allow_update_actions" boolean NOT NULL DEFAULT true, "allow_delete_actions" boolean NOT NULL DEFAULT false, "allow_execute_actions" boolean NOT NULL DEFAULT true, "default_requires_confirmation" boolean NOT NULL DEFAULT true, "system_read_only_collections" jsonb NOT NULL DEFAULT '[]', "user_rate_limit_per_hour" integer NOT NULL DEFAULT '100', "global_rate_limit_per_hour" integer NOT NULL DEFAULT '10000', "updated_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ae7c69697b886ebe857e9e15239" PRIMARY KEY ("id"))`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da27d912745ad6fae4eaaf07d3"`);
        await queryRunner.query(`CREATE INDEX "IDX_da27d912745ad6fae4eaaf07d3" ON "user_roles" ("valid_from", "valid_until") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_fba2d8e029689aa8fea98e53c91" FOREIGN KEY ("manager_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_d2dbc280ebc69071c0846c87019" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a9add0cb9d63c590d8aedeceecb" FOREIGN KEY ("deactivated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_84808507d893ed21a8b8253d6bc" FOREIGN KEY ("suspended_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_021e2c9d9dca9f0885e8d738326" FOREIGN KEY ("deleted_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_a731453130efd9b40d4ab5f9620" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_947e863084a338ac018f1beab96" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_3e97eeaf865aeda0d20c0c5c509" FOREIGN KEY ("parent_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_4a39f3095781cdd9d6061afaae5" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_747b580d73db0ad78963d78b076" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_d768ea35a407c2ba9c0b038b613" FOREIGN KEY ("parent_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_a2fa29bfd5351b5b7ccacbc9f7c" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_2c840df5db52dc6b4a1b0b69c6e" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_20a555b299f75843aa53ff8b0ee" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_4ad0de0815545b0c63e2b86250c" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_roles" ADD CONSTRAINT "FK_0f428ea82b51ea6c795689cdb8a" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_roles" ADD CONSTRAINT "FK_35d4b5f7da6e1a9a730c3621ecc" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_roles" ADD CONSTRAINT "FK_14ee449cf1a7a0e879b54fd5626" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "choice_items" ADD CONSTRAINT "FK_98334e02c5109bd3a8ec155c2bd" FOREIGN KEY ("choice_list_id") REFERENCES "choice_lists"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_definitions" ADD CONSTRAINT "FK_2e4c4613796c3af281556a2b62c" FOREIGN KEY ("collection_id") REFERENCES "collection_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_definitions" ADD CONSTRAINT "FK_10dab69d18bbe034d20839f2adf" FOREIGN KEY ("property_type_id") REFERENCES "property_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_definitions" ADD CONSTRAINT "FK_e7ba7ffa905aec05e0791992923" FOREIGN KEY ("reference_collection_id") REFERENCES "collection_definitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_definitions" ADD CONSTRAINT "FK_c88d8fdd8f9688600a99b0b9711" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_definitions" ADD CONSTRAINT "FK_ed35ee925189245000d53d91490" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_definitions" ADD CONSTRAINT "FK_c38e77b7b225ba65cddbf6e10a8" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_access_rules" ADD CONSTRAINT "FK_0644be2a2e4d4a95dae2039d044" FOREIGN KEY ("collection_id") REFERENCES "collection_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_access_rules" ADD CONSTRAINT "FK_0ee922b564bc954b4d97eae8154" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_access_rules" ADD CONSTRAINT "FK_d9437ad9cb5e4aedaf442b949e5" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_access_rules" ADD CONSTRAINT "FK_2bbd90ecb185529732938857fa3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_access_rules" ADD CONSTRAINT "FK_0716029d0918b15af5c777d3b19" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_access_rules" ADD CONSTRAINT "FK_314d7767bd038e2d47aebb208f5" FOREIGN KEY ("property_id") REFERENCES "property_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_access_rules" ADD CONSTRAINT "FK_0189d2c9de5f8ef47506294a27f" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_access_rules" ADD CONSTRAINT "FK_a0b9e97943e753481035a49922f" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_access_rules" ADD CONSTRAINT "FK_8c5f3ff32b318d551d8f4a7b280" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_events" ADD CONSTRAINT "FK_d27703f0a3d79ba424741807cb4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nav_profiles" ADD CONSTRAINT "FK_1520f8f695df6f299c14f4f1fcc" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nav_profiles" ADD CONSTRAINT "FK_c2791c2beecf130b1bf94bb42a3" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nav_profiles" ADD CONSTRAINT "FK_77d64f0d70a0883578f4436a804" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nav_profile_items" ADD CONSTRAINT "FK_f02d51b25f5821bc1ee6780cc1b" FOREIGN KEY ("profile_id") REFERENCES "nav_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nav_profile_items" ADD CONSTRAINT "FK_e61477461f4ab1ba6729234fe47" FOREIGN KEY ("parent_id") REFERENCES "nav_profile_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_history" ADD CONSTRAINT "FK_4933dc7a01356ac0733a5ad52d9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" ADD CONSTRAINT "FK_fdcb77f72f529bf65c95d72a147" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_a3baee01d8408cd3c0f89a9a973" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_invitations" ADD CONSTRAINT "FK_18241a1a2cb2d284716636b2340" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mfa_methods" ADD CONSTRAINT "FK_1d590a89ba342ab3515e64f6d28" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "theme_definitions" ADD CONSTRAINT "FK_53431368019d2e12f9db8bee72a" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_theme_preferences" ADD CONSTRAINT "FK_ae77cd7cd68614f5880e1027574" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_theme_preferences" ADD CONSTRAINT "FK_15ec7ebb4783b5d71df82027898" FOREIGN KEY ("theme_id") REFERENCES "theme_definitions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instance_branding" ADD CONSTRAINT "FK_ce407c1aa6965b7f4667e1c2385" FOREIGN KEY ("default_theme_id") REFERENCES "theme_definitions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "FK_458057fa75b66e68a275647da2e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "module_security" ADD CONSTRAINT "FK_476979d5494d0697ddd56dd94c8" FOREIGN KEY ("module_id") REFERENCES "modules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "module_security" ADD CONSTRAINT "FK_6b88a58f364d05ef36ab89d3534" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD CONSTRAINT "FK_111982cc806d8c26c9c445ece75" FOREIGN KEY ("collection_id") REFERENCES "collection_definitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_versions" ADD CONSTRAINT "FK_5270f702bc84ac42d6211ce4478" FOREIGN KEY ("form_id") REFERENCES "form_definitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "form_versions" DROP CONSTRAINT "FK_5270f702bc84ac42d6211ce4478"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP CONSTRAINT "FK_111982cc806d8c26c9c445ece75"`);
        await queryRunner.query(`ALTER TABLE "module_security" DROP CONSTRAINT "FK_6b88a58f364d05ef36ab89d3534"`);
        await queryRunner.query(`ALTER TABLE "module_security" DROP CONSTRAINT "FK_476979d5494d0697ddd56dd94c8"`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "FK_458057fa75b66e68a275647da2e"`);
        await queryRunner.query(`ALTER TABLE "instance_branding" DROP CONSTRAINT "FK_ce407c1aa6965b7f4667e1c2385"`);
        await queryRunner.query(`ALTER TABLE "user_theme_preferences" DROP CONSTRAINT "FK_15ec7ebb4783b5d71df82027898"`);
        await queryRunner.query(`ALTER TABLE "user_theme_preferences" DROP CONSTRAINT "FK_ae77cd7cd68614f5880e1027574"`);
        await queryRunner.query(`ALTER TABLE "theme_definitions" DROP CONSTRAINT "FK_53431368019d2e12f9db8bee72a"`);
        await queryRunner.query(`ALTER TABLE "mfa_methods" DROP CONSTRAINT "FK_1d590a89ba342ab3515e64f6d28"`);
        await queryRunner.query(`ALTER TABLE "user_invitations" DROP CONSTRAINT "FK_18241a1a2cb2d284716636b2340"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_a3baee01d8408cd3c0f89a9a973"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" DROP CONSTRAINT "FK_fdcb77f72f529bf65c95d72a147"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c"`);
        await queryRunner.query(`ALTER TABLE "password_history" DROP CONSTRAINT "FK_4933dc7a01356ac0733a5ad52d9"`);
        await queryRunner.query(`ALTER TABLE "nav_profile_items" DROP CONSTRAINT "FK_e61477461f4ab1ba6729234fe47"`);
        await queryRunner.query(`ALTER TABLE "nav_profile_items" DROP CONSTRAINT "FK_f02d51b25f5821bc1ee6780cc1b"`);
        await queryRunner.query(`ALTER TABLE "nav_profiles" DROP CONSTRAINT "FK_77d64f0d70a0883578f4436a804"`);
        await queryRunner.query(`ALTER TABLE "nav_profiles" DROP CONSTRAINT "FK_c2791c2beecf130b1bf94bb42a3"`);
        await queryRunner.query(`ALTER TABLE "nav_profiles" DROP CONSTRAINT "FK_1520f8f695df6f299c14f4f1fcc"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "auth_events" DROP CONSTRAINT "FK_d27703f0a3d79ba424741807cb4"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_e9658e959c490b0a634dfc54783"`);
        await queryRunner.query(`ALTER TABLE "property_access_rules" DROP CONSTRAINT "FK_8c5f3ff32b318d551d8f4a7b280"`);
        await queryRunner.query(`ALTER TABLE "property_access_rules" DROP CONSTRAINT "FK_a0b9e97943e753481035a49922f"`);
        await queryRunner.query(`ALTER TABLE "property_access_rules" DROP CONSTRAINT "FK_0189d2c9de5f8ef47506294a27f"`);
        await queryRunner.query(`ALTER TABLE "property_access_rules" DROP CONSTRAINT "FK_314d7767bd038e2d47aebb208f5"`);
        await queryRunner.query(`ALTER TABLE "collection_access_rules" DROP CONSTRAINT "FK_0716029d0918b15af5c777d3b19"`);
        await queryRunner.query(`ALTER TABLE "collection_access_rules" DROP CONSTRAINT "FK_2bbd90ecb185529732938857fa3"`);
        await queryRunner.query(`ALTER TABLE "collection_access_rules" DROP CONSTRAINT "FK_d9437ad9cb5e4aedaf442b949e5"`);
        await queryRunner.query(`ALTER TABLE "collection_access_rules" DROP CONSTRAINT "FK_0ee922b564bc954b4d97eae8154"`);
        await queryRunner.query(`ALTER TABLE "collection_access_rules" DROP CONSTRAINT "FK_0644be2a2e4d4a95dae2039d044"`);
        await queryRunner.query(`ALTER TABLE "collection_definitions" DROP CONSTRAINT "FK_c38e77b7b225ba65cddbf6e10a8"`);
        await queryRunner.query(`ALTER TABLE "collection_definitions" DROP CONSTRAINT "FK_ed35ee925189245000d53d91490"`);
        await queryRunner.query(`ALTER TABLE "property_definitions" DROP CONSTRAINT "FK_c88d8fdd8f9688600a99b0b9711"`);
        await queryRunner.query(`ALTER TABLE "property_definitions" DROP CONSTRAINT "FK_e7ba7ffa905aec05e0791992923"`);
        await queryRunner.query(`ALTER TABLE "property_definitions" DROP CONSTRAINT "FK_10dab69d18bbe034d20839f2adf"`);
        await queryRunner.query(`ALTER TABLE "property_definitions" DROP CONSTRAINT "FK_2e4c4613796c3af281556a2b62c"`);
        await queryRunner.query(`ALTER TABLE "choice_items" DROP CONSTRAINT "FK_98334e02c5109bd3a8ec155c2bd"`);
        await queryRunner.query(`ALTER TABLE "group_roles" DROP CONSTRAINT "FK_14ee449cf1a7a0e879b54fd5626"`);
        await queryRunner.query(`ALTER TABLE "group_roles" DROP CONSTRAINT "FK_35d4b5f7da6e1a9a730c3621ecc"`);
        await queryRunner.query(`ALTER TABLE "group_roles" DROP CONSTRAINT "FK_0f428ea82b51ea6c795689cdb8a"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_4ad0de0815545b0c63e2b86250c"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_20a555b299f75843aa53ff8b0ee"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_2c840df5db52dc6b4a1b0b69c6e"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_a2fa29bfd5351b5b7ccacbc9f7c"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_d768ea35a407c2ba9c0b038b613"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_747b580d73db0ad78963d78b076"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_4a39f3095781cdd9d6061afaae5"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_3e97eeaf865aeda0d20c0c5c509"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_947e863084a338ac018f1beab96"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_a731453130efd9b40d4ab5f9620"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_021e2c9d9dca9f0885e8d738326"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_84808507d893ed21a8b8253d6bc"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a9add0cb9d63c590d8aedeceecb"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_d2dbc280ebc69071c0846c87019"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_fba2d8e029689aa8fea98e53c91"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da27d912745ad6fae4eaaf07d3"`);
        await queryRunner.query(`CREATE INDEX "IDX_da27d912745ad6fae4eaaf07d3" ON "user_roles" ("valid_from", "valid_until") `);
        await queryRunner.query(`DROP TABLE "ava_global_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cd7923ae0d32881a0d82c0280"`);
        await queryRunner.query(`DROP TABLE "ava_permission_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1702c609e880eb3d176d060ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97c0f7d7333849f12e42cf7779"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a388db879a8dcc4ccdb37264fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_106f148639500d8a937386b5a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f57eac7ca7c67e6dc24f2f1be1"`);
        await queryRunner.query(`DROP TABLE "ava_audit_trail"`);
        await queryRunner.query(`DROP TABLE "property_audit_logs"`);
        await queryRunner.query(`DROP TABLE "access_audit_logs"`);
        await queryRunner.query(`DROP TABLE "access_rule_audit_logs"`);
        await queryRunner.query(`DROP TABLE "form_versions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_111982cc806d8c26c9c445ece7"`);
        await queryRunner.query(`DROP TABLE "form_definitions"`);
        await queryRunner.query(`DROP TABLE "module_security"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a57f2b3bd9ebb022212e634f60"`);
        await queryRunner.query(`DROP TABLE "modules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_458057fa75b66e68a275647da2"`);
        await queryRunner.query(`DROP TABLE "user_preferences"`);
        await queryRunner.query(`DROP TABLE "instance_branding"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae77cd7cd68614f5880e102757"`);
        await queryRunner.query(`DROP TABLE "user_theme_preferences"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7acdb47306e9b04ff598ca67a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0a7ca386aca61a735377afe1d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8553e254fab743a15789c9367"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05cbb2665b2c235e3c06f0e55b"`);
        await queryRunner.query(`DROP TABLE "theme_definitions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d590a89ba342ab3515e64f6d2"`);
        await queryRunner.query(`DROP TABLE "mfa_methods"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d818b0ebcc97ef5dfb67fb7867"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c885f83eb2a34fedd887e43e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_245772caab09e629f6e80aaaba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f3ae879cf24686834c974effd"`);
        await queryRunner.query(`DROP TABLE "user_invitations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3baee01d8408cd3c0f89a9a97"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57384430aa1959f4578046c9b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_138cc6196c7bfa61d31412aea7"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4542dd2f38a61354a040ba9fd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba3bd69c8ad1e799c0256e9e50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a5f57e17354e7407757e8793b"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fdcb77f72f529bf65c95d72a14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d1613f95c6a564a3b588d161a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7c64ecae33a54d3a11a4e6b6e"`);
        await queryRunner.query(`DROP TABLE "email_verification_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52ac39dd8a28730c63aeb428c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab673f0e63eac966762155508e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c038e5a589b06cbe4320cc88b"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4933dc7a01356ac0733a5ad52d"`);
        await queryRunner.query(`DROP TABLE "password_history"`);
        await queryRunner.query(`DROP TABLE "config_change_history"`);
        await queryRunner.query(`DROP TABLE "instance_customizations"`);
        await queryRunner.query(`DROP TABLE "sso_providers"`);
        await queryRunner.query(`DROP TABLE "ldap_configs"`);
        await queryRunner.query(`DROP TABLE "password_policies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c03e48624b266373a313f87d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4841fbd4c9819d5ade4b5dfeb"`);
        await queryRunner.query(`DROP TABLE "instance_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f02d51b25f5821bc1ee6780cc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e61477461f4ab1ba6729234fe4"`);
        await queryRunner.query(`DROP TABLE "nav_profile_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92556f552f70c0531bdf4fc9d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4db63a99d84dfd65fe3dca1bb2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_296ff17c5fdac130091f783281"`);
        await queryRunner.query(`DROP TABLE "nav_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bacca40d90fcebfc311982eb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0acee5e593954a1dc4ac8aad3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d27703f0a3d79ba424741807cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aff0693e5ee9e891fcdb414daa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64ac9bded13b2b6b75b128d8e5"`);
        await queryRunner.query(`DROP TABLE "auth_events"`);
        await queryRunner.query(`DROP TABLE "auth_settings"`);
        await queryRunner.query(`DROP TABLE "access_condition_groups"`);
        await queryRunner.query(`DROP TABLE "access_conditions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9658e959c490b0a634dfc5478"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5eb7a3c7766f941fe16b9edec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbc81ff542b1b3366bae195f2a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c30b2278a5d31e23fcaee4887"`);
        await queryRunner.query(`DROP TABLE "user_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_314d7767bd038e2d47aebb208f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0189d2c9de5f8ef47506294a27"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0b9e97943e753481035a49922"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c5f3ff32b318d551d8f4a7b28"`);
        await queryRunner.query(`DROP TABLE "property_access_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0644be2a2e4d4a95dae2039d04"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ee922b564bc954b4d97eae815"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9437ad9cb5e4aedaf442b949e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2bbd90ecb185529732938857fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52174f0e91e1a5a0c87c9fcf78"`);
        await queryRunner.query(`DROP TABLE "collection_access_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d74cad0dd7ab2f1144e34e1a81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c22e7ac994b29b2d8320bf3bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d816b7a55d18d87ca3b6065a49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d24aec9ddb25523068aefad8c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e317662a80e3314c64265c35e9"`);
        await queryRunner.query(`DROP TABLE "collection_definitions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e4c4613796c3af281556a2b62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10dab69d18bbe034d20839f2ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7ba7ffa905aec05e079199292"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16cc6ea2ff3b1429345831f1f9"`);
        await queryRunner.query(`DROP TABLE "property_definitions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98334e02c5109bd3a8ec155c2b"`);
        await queryRunner.query(`DROP TABLE "choice_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_931628f1c40bc1d2b193ee0756"`);
        await queryRunner.query(`DROP TABLE "choice_lists"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f7b17d42cf5cbd751912ddda1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b03cfc29a73bc8ab5edf39c826"`);
        await queryRunner.query(`DROP TABLE "property_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f428ea82b51ea6c795689cdb8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35d4b5f7da6e1a9a730c3621ec"`);
        await queryRunner.query(`DROP TABLE "group_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c840df5db52dc6b4a1b0b69c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20a555b299f75843aa53ff8b0e"`);
        await queryRunner.query(`DROP TABLE "group_members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8989cafa0945a366f0c8716e60"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d768ea35a407c2ba9c0b038b61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b343e4f936b28da5922520105"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed580a627f0d82d392897b4bca"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6d54f95c31b73fb1bdd8e91d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e97eeaf865aeda0d20c0c5c50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a3edd7bc16920c3287331ea42"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9f58bffa9bdcc402c0438a60c"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da27d912745ad6fae4eaaf07d3"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8dad765629e83229da6feda1c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aad80a27f0a425bfc3f092a732"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_637007c67b604bd971d4fe6823"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7fdbf1baeb91b6f822b5d57e19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01b38a262e9036dfcd0d686de6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0837b566b883183034a42db0e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3676155292d72c67cd4e090514"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c162e1fe9d744b0721daea3b1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fba2d8e029689aa8fea98e53c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b7c676ffb354a9cabc87b7da9"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
