apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
  selector:
    {{- include "control-plane.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
  selector:
    {{- include "control-plane.selectorLabels" (dict "root" . "component" "web") | nindent 4 }}
