import { MigrationInterface, QueryRunner } from "typeorm";

export class InitTenant1764729687516 implements MigrationInterface {
    name = 'InitTenant1764729687516'

    public async up(queryRunner: QueryRunner): Promise<void> {
        const hasFormDefinitions = await queryRunner.hasTable('form_definitions');
        const hasLegacyTenantId = hasFormDefinitions
            ? await queryRunner.hasColumn('form_definitions', 'tenantId')
            : false;
        if (!hasLegacyTenantId) {
            // Fresh schema is handled by newer baseline migrations; skip legacy transforms.
            return;
        }
        await queryRunner.query(`ALTER TABLE "form_versions" DROP CONSTRAINT "form_versions_formId_fkey"`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" DROP CONSTRAINT "workflow_runs_workflowId_fkey"`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP CONSTRAINT "model_table_extends_table_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP CONSTRAINT "model_field_table_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP CONSTRAINT "model_field_field_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "model_form_layout" DROP CONSTRAINT "model_form_layout_tableId_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_data_objects_table"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_log_table"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_log_record"`);
        await queryRunner.query(`DROP INDEX "public"."idx_model_form_layout_table"`);
        await queryRunner.query(`ALTER TABLE "modules" DROP CONSTRAINT "uq_modules_tenant_slug"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP CONSTRAINT "uq_form_definitions_tenant_slug"`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP CONSTRAINT "uq_workflow_definitions_tenant_slug"`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP CONSTRAINT "uq_model_field_table_code"`);
        await queryRunner.query(`ALTER TABLE "model_form_layout" DROP CONSTRAINT "uq_model_form_layout_table_name"`);
        await queryRunner.query(`CREATE TABLE "user_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "email" character varying, "displayName" character varying, "authSource" character varying NOT NULL DEFAULT 'LOCAL', "passwordHash" character varying, "previousPasswords" text NOT NULL DEFAULT '', "failedLoginCount" integer NOT NULL DEFAULT '0', "lastFailedLoginAt" TIMESTAMP, "lockedUntil" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'ACTIVE', "emailVerified" boolean NOT NULL DEFAULT false, "passwordChangedAt" TIMESTAMP WITH TIME ZONE, "lastLoginAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_125e915cf23ad1cfb43815ce59b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d45e7ca4a62293443961558c56" ON "user_accounts" ("username") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "permissions" text NOT NULL DEFAULT '', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "category" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_role_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "roleId" uuid NOT NULL, CONSTRAINT "PK_ac634a3aa59d70bf0fb7b423b47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_664ea405ae2a10c264d582ee56" ON "groups" ("name") `);
        await queryRunner.query(`CREATE TABLE "user_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "groupId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dc24675c437bf3c70d3d0dff67f" UNIQUE ("userId", "groupId"), CONSTRAINT "PK_ea7760dc75ee1bf0b09ab9b3289" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "groupId" uuid NOT NULL, "roleId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_681b827dab7faf2f26680850743" UNIQUE ("groupId", "roleId"), CONSTRAINT "PK_c88b2351f40bf170bc7ab7e8fda" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "minLength" integer NOT NULL DEFAULT '12', "requireUppercase" boolean NOT NULL DEFAULT true, "requireLowercase" boolean NOT NULL DEFAULT true, "requireNumbers" boolean NOT NULL DEFAULT true, "requireSymbols" boolean NOT NULL DEFAULT false, "passwordExpiryDays" integer NOT NULL DEFAULT '0', "passwordHistoryDepth" integer NOT NULL DEFAULT '5', "maxFailedAttempts" integer NOT NULL DEFAULT '5', "lockoutDurationMinutes" integer NOT NULL DEFAULT '15', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5468b65a86afc8563ac81cb9153" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tokenHash" character varying NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "revokedAt" TIMESTAMP WITH TIME ZONE, "replacedByToken" character varying, "ipAddress" character varying, "userAgent" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c25bc63d248ca90e8dcc1d92d06" UNIQUE ("tokenHash"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fd99bb073033ec13353c5f62c5" ON "refresh_tokens" ("userId", "revoked") `);
        await queryRunner.query(`CREATE TABLE "mfa_methods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" character varying NOT NULL, "enabled" boolean NOT NULL DEFAULT false, "verified" boolean NOT NULL DEFAULT false, "secret" character varying, "destination" character varying, "recoveryCodes" text NOT NULL DEFAULT '', "lastUsedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_60e4d183e6dbd427aa5549da581" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b8cf794d73ba5870a92032da94" ON "mfa_methods" ("userId", "type") `);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tokenHash" character varying NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "used" boolean NOT NULL DEFAULT false, "usedAt" TIMESTAMP WITH TIME ZONE, "ipAddress" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1143abb8c3fad8b06dd857a8c9c" UNIQUE ("tokenHash"), CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9bfba70726ffca74288d85e6fd" ON "password_reset_tokens" ("userId", "used") `);
        await queryRunner.query(`CREATE TABLE "email_verification_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tokenHash" character varying NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "used" boolean NOT NULL DEFAULT false, "usedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_90489f8f3368c45f461e90efbe5" UNIQUE ("tokenHash"), CONSTRAINT "PK_417a095bbed21c2369a6a01ab9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aee6bd8cf4c84b0a0561adfe0e" ON "email_verification_tokens" ("userId", "used") `);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "keyPrefix" character varying NOT NULL, "keyHash" character varying NOT NULL, "scopes" text NOT NULL DEFAULT '', "expiresAt" TIMESTAMP, "lastUsedAt" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auth_ldap_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "enabled" boolean NOT NULL DEFAULT false, "name" character varying NOT NULL, "host" character varying NOT NULL, "bindDn" character varying NOT NULL, "bindPassword" character varying NOT NULL, "userBaseDn" character varying NOT NULL, "userFilter" character varying NOT NULL DEFAULT '(uid={username})', "mapUsernameAttr" character varying NOT NULL DEFAULT 'uid', "mapEmailAttr" character varying NOT NULL DEFAULT 'mail', "mapDisplayNameAttr" character varying NOT NULL DEFAULT 'cn', "timeoutMs" integer NOT NULL DEFAULT '5000', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_90986c98ae492dc5f1128db80e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auth_sso_provider" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "enabled" boolean NOT NULL DEFAULT false, "name" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'OIDC', "issuerUrl" character varying NOT NULL, "clientId" character varying NOT NULL, "clientSecret" character varying NOT NULL, "redirectUri" character varying NOT NULL, "mapUsernameClaim" character varying NOT NULL DEFAULT 'preferred_username', "mapEmailClaim" character varying NOT NULL DEFAULT 'email', "mapDisplayNameClaim" character varying NOT NULL DEFAULT 'name', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2f5ca268f5196113d6aa752109c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "abac_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "resource" character varying NOT NULL, "action" character varying NOT NULL, "effect" character varying NOT NULL DEFAULT 'allow', "conditions" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_97380849c09333fdd772a2e9c2a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_af551834b45f1c593ce39da4cf" ON "abac_policies" ("resource", "action") `);
        await queryRunner.query(`CREATE TABLE "config_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scope" character varying NOT NULL, "category" character varying NOT NULL, "key" character varying NOT NULL, "type" character varying NOT NULL, "value" jsonb NOT NULL, "version" integer NOT NULL DEFAULT '1', "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4028e0f2bb7ee5e2679f9008c62" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5d0213ac2ba49fada349fe3101" ON "config_settings" ("scope", "key") `);
        await queryRunner.query(`CREATE TABLE "tenant_theme" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" text, "tokens" jsonb NOT NULL DEFAULT '{}', "nav_variant" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, CONSTRAINT "PK_b488a6c4f68d1c4f42bdb8d90c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "nav_profile_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "profile_id" uuid NOT NULL, "code" text NOT NULL, "label" text, "section" text, "order" integer NOT NULL DEFAULT '999', "visible" boolean NOT NULL DEFAULT true, "pinned" boolean NOT NULL DEFAULT false, "icon" text, "profileId" uuid, CONSTRAINT "PK_ba4afca064db77c224ebff49d56" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "nav_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" text, "is_default" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_969f289499d47544ba67bd7a502" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "table_definitions" DROP CONSTRAINT "table_definitions_tableName_key"`);
        await queryRunner.query(`ALTER TABLE "table_definitions" DROP COLUMN "tableName"`);
        await queryRunner.query(`ALTER TABLE "table_definitions" ADD "tableName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "table_definitions" ADD CONSTRAINT "UQ_27ef931e66d8b22d78acd6073a3" UNIQUE ("tableName")`);
        await queryRunner.query(`ALTER TABLE "table_definitions" DROP COLUMN "displayName"`);
        await queryRunner.query(`ALTER TABLE "table_definitions" ADD "displayName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "table_definitions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "table_definitions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "table_definitions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "table_definitions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_objects" DROP COLUMN "tableName"`);
        await queryRunner.query(`ALTER TABLE "data_objects" ADD "tableName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "data_objects" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "data_objects" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_objects" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "data_objects" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "slug" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "route"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "route" character varying`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "icon"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "icon" character varying`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "category" character varying`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD "slug" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_versions" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "form_versions" ADD "createdBy" character varying`);
        await queryRunner.query(`ALTER TABLE "form_versions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "form_versions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_versions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "form_versions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD "slug" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" DROP COLUMN "error"`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" ADD "error" character varying`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP CONSTRAINT "model_field_type_code_key"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD CONSTRAINT "UQ_056a0edfe06e4660877ca2f6e56" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "label"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "label" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "category" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "backend_type"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "backend_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "ui_widget"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "ui_widget" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP CONSTRAINT "model_table_code_key"`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD CONSTRAINT "UQ_11b764fbebdce2e75881b8bf175" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "label"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "label" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "category" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "storage_schema"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "storage_schema" character varying NOT NULL DEFAULT 'public'`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "storage_table"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "storage_table" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD "code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP COLUMN "label"`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD "label" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP COLUMN "default_value"`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD "default_value" character varying`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP COLUMN "storage_path"`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD "storage_path" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "tableName"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "tableName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "recordId"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "recordId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "action" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "performedBy"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "performedBy" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "timestamp"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_form_layout" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "model_form_layout" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_a2ec3f949b5fa2f4fdf9d4f264" ON "data_objects" ("tableName") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_503404f7e2e602815906fa62e5" ON "modules" ("slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5f63f92ffd7a77edbcdb554aec" ON "form_definitions" ("slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_19f73bde8c6beae73579ff80d3" ON "workflow_definitions" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_d465cfbb1f58c229678e8d800e" ON "audit_log" ("tableName") `);
        await queryRunner.query(`CREATE INDEX "IDX_41231b41981bfa3de6ebcc0d0b" ON "audit_log" ("recordId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef968475e513c7d117771a5736" ON "model_form_layout" ("tableId") `);
        await queryRunner.query(`ALTER TABLE "model_field" ADD CONSTRAINT "UQ_1c6ff90f1d4e670ddac9a036811" UNIQUE ("table_id", "code")`);
        await queryRunner.query(`ALTER TABLE "form_versions" ADD CONSTRAINT "FK_4f22a570ecaca0bee93bbf1a3c7" FOREIGN KEY ("formId") REFERENCES "form_definitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" ADD CONSTRAINT "FK_986cbc17e1a918a606cdc4be142" FOREIGN KEY ("workflowId") REFERENCES "workflow_definitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD CONSTRAINT "FK_f6ce680cd565a7c2c2d060e1f6f" FOREIGN KEY ("extends_table_id") REFERENCES "model_table"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD CONSTRAINT "FK_e75936045c22d649db0ea7ee8a5" FOREIGN KEY ("table_id") REFERENCES "model_table"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD CONSTRAINT "FK_ae7ef02fef2f3942f05b67189a8" FOREIGN KEY ("field_type_id") REFERENCES "model_field_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "model_form_layout" ADD CONSTRAINT "FK_ef968475e513c7d117771a5736e" FOREIGN KEY ("tableId") REFERENCES "table_definitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role_assignments" ADD CONSTRAINT "FK_207bd1768c9fa4f9e9132e60a84" FOREIGN KEY ("userId") REFERENCES "user_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role_assignments" ADD CONSTRAINT "FK_78d72d76584e98654584fbb33c0" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_groups" ADD CONSTRAINT "FK_99d01ff7f143377c044f3d6c955" FOREIGN KEY ("userId") REFERENCES "user_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_groups" ADD CONSTRAINT "FK_4dcea3f5c6f04650517d9dc4750" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_roles" ADD CONSTRAINT "FK_2b5f930e296a7d2bf3b14e59f42" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_roles" ADD CONSTRAINT "FK_69f84cc2625ddd7555de6ee7458" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "user_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mfa_methods" ADD CONSTRAINT "FK_da5c673799e2d10e329af2dd1be" FOREIGN KEY ("userId") REFERENCES "user_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2" FOREIGN KEY ("userId") REFERENCES "user_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" ADD CONSTRAINT "FK_10f285d038feb767bf7c2da14b3" FOREIGN KEY ("userId") REFERENCES "user_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nav_profile_item" ADD CONSTRAINT "FK_30ff80c18e8c4727629c19a486b" FOREIGN KEY ("profileId") REFERENCES "nav_profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "nav_profile_item" DROP CONSTRAINT "FK_30ff80c18e8c4727629c19a486b"`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" DROP CONSTRAINT "FK_10f285d038feb767bf7c2da14b3"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2"`);
        await queryRunner.query(`ALTER TABLE "mfa_methods" DROP CONSTRAINT "FK_da5c673799e2d10e329af2dd1be"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "group_roles" DROP CONSTRAINT "FK_69f84cc2625ddd7555de6ee7458"`);
        await queryRunner.query(`ALTER TABLE "group_roles" DROP CONSTRAINT "FK_2b5f930e296a7d2bf3b14e59f42"`);
        await queryRunner.query(`ALTER TABLE "user_groups" DROP CONSTRAINT "FK_4dcea3f5c6f04650517d9dc4750"`);
        await queryRunner.query(`ALTER TABLE "user_groups" DROP CONSTRAINT "FK_99d01ff7f143377c044f3d6c955"`);
        await queryRunner.query(`ALTER TABLE "user_role_assignments" DROP CONSTRAINT "FK_78d72d76584e98654584fbb33c0"`);
        await queryRunner.query(`ALTER TABLE "user_role_assignments" DROP CONSTRAINT "FK_207bd1768c9fa4f9e9132e60a84"`);
        await queryRunner.query(`ALTER TABLE "model_form_layout" DROP CONSTRAINT "FK_ef968475e513c7d117771a5736e"`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP CONSTRAINT "FK_ae7ef02fef2f3942f05b67189a8"`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP CONSTRAINT "FK_e75936045c22d649db0ea7ee8a5"`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP CONSTRAINT "FK_f6ce680cd565a7c2c2d060e1f6f"`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" DROP CONSTRAINT "FK_986cbc17e1a918a606cdc4be142"`);
        await queryRunner.query(`ALTER TABLE "form_versions" DROP CONSTRAINT "FK_4f22a570ecaca0bee93bbf1a3c7"`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP CONSTRAINT "UQ_1c6ff90f1d4e670ddac9a036811"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef968475e513c7d117771a5736"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41231b41981bfa3de6ebcc0d0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d465cfbb1f58c229678e8d800e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19f73bde8c6beae73579ff80d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f63f92ffd7a77edbcdb554aec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_503404f7e2e602815906fa62e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2ec3f949b5fa2f4fdf9d4f264"`);
        await queryRunner.query(`ALTER TABLE "model_form_layout" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "model_form_layout" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "timestamp"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "performedBy"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "performedBy" text`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "action" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "recordId"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "recordId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "tableName"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "tableName" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP COLUMN "storage_path"`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD "storage_path" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP COLUMN "default_value"`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD "default_value" text`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP COLUMN "label"`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD "label" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD "code" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "storage_table"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "storage_table" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "storage_schema"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "storage_schema" text NOT NULL DEFAULT 'public'`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "category" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "label"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "label" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP CONSTRAINT "UQ_11b764fbebdce2e75881b8bf175"`);
        await queryRunner.query(`ALTER TABLE "model_table" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD "code" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD CONSTRAINT "model_table_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "ui_widget"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "ui_widget" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "backend_type"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "backend_type" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "category" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "label"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "label" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP CONSTRAINT "UQ_056a0edfe06e4660877ca2f6e56"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD "code" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_field_type" ADD CONSTRAINT "model_field_type_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" DROP COLUMN "error"`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" ADD "error" text`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD "slug" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_versions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "form_versions" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_versions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "form_versions" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_versions" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "form_versions" ADD "createdBy" uuid`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD "slug" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "form_definitions" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "category" text`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "icon"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "icon" text`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "route"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "route" text`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "slug" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "modules" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "data_objects" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "data_objects" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_objects" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "data_objects" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_objects" DROP COLUMN "tableName"`);
        await queryRunner.query(`ALTER TABLE "data_objects" ADD "tableName" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "table_definitions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "table_definitions" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "table_definitions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "table_definitions" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "table_definitions" DROP COLUMN "displayName"`);
        await queryRunner.query(`ALTER TABLE "table_definitions" ADD "displayName" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "table_definitions" DROP CONSTRAINT "UQ_27ef931e66d8b22d78acd6073a3"`);
        await queryRunner.query(`ALTER TABLE "table_definitions" DROP COLUMN "tableName"`);
        await queryRunner.query(`ALTER TABLE "table_definitions" ADD "tableName" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "table_definitions" ADD CONSTRAINT "table_definitions_tableName_key" UNIQUE ("tableName")`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD "tenantId" uuid`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD "tenantId" uuid`);
        await queryRunner.query(`ALTER TABLE "modules" ADD "tenantId" uuid`);

        await queryRunner.query(`ALTER TABLE "model_form_layout" ADD CONSTRAINT "uq_model_form_layout_table_name" UNIQUE ("tableId", "name")`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD CONSTRAINT "uq_model_field_table_code" UNIQUE ("table_id", "code")`);
        await queryRunner.query(`ALTER TABLE "workflow_definitions" ADD CONSTRAINT "uq_workflow_definitions_tenant_slug" UNIQUE ("tenantId", "slug")`);
        await queryRunner.query(`ALTER TABLE "form_definitions" ADD CONSTRAINT "uq_form_definitions_tenant_slug" UNIQUE ("tenantId", "slug")`);
        await queryRunner.query(`ALTER TABLE "modules" ADD CONSTRAINT "uq_modules_tenant_slug" UNIQUE ("tenantId", "slug")`);
        await queryRunner.query(`CREATE INDEX "idx_model_form_layout_table" ON "model_form_layout" ("tableId") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_log_record" ON "audit_log" ("recordId") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_log_table" ON "audit_log" ("tableName") `);
        await queryRunner.query(`CREATE INDEX "idx_data_objects_table" ON "data_objects" ("tableName") `);
        await queryRunner.query(`ALTER TABLE "model_form_layout" ADD CONSTRAINT "model_form_layout_tableId_fkey" FOREIGN KEY ("tableId") REFERENCES "table_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD CONSTRAINT "model_field_field_type_id_fkey" FOREIGN KEY ("field_type_id") REFERENCES "model_field_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "model_field" ADD CONSTRAINT "model_field_table_id_fkey" FOREIGN KEY ("table_id") REFERENCES "model_table"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "model_table" ADD CONSTRAINT "model_table_extends_table_id_fkey" FOREIGN KEY ("extends_table_id") REFERENCES "model_table"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_runs" ADD CONSTRAINT "workflow_runs_workflowId_fkey" FOREIGN KEY ("workflowId") REFERENCES "workflow_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_versions" ADD CONSTRAINT "form_versions_formId_fkey" FOREIGN KEY ("formId") REFERENCES "form_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
