/**
 * Generates a fresh set of internal-only secrets for local development.
 *
 * Run once on a fresh checkout:
 *   npx ts-node scripts/generate-local-dev-secrets.ts >> .env
 *
 * Then review the appended block in .env, fill in the external-service
 * tokens manually (Cloudflare, HuggingFace, Anthropic, OpenAI, etc.),
 * and bring up the stack.
 *
 * Production secrets MUST come from your platform secrets store (AWS
 * Secrets Manager, k8s sealed-secrets, etc.) — never from this script.
 */

import { generateKeyPairSync, randomBytes } from 'crypto';

function hex(bytes: number): string {
  return randomBytes(bytes).toString('hex');
}

function base64(bytes: number): string {
  return randomBytes(bytes).toString('base64');
}

function generateEd25519PemPair(): { publicKey: string; privateKey: string } {
  const { publicKey, privateKey } = generateKeyPairSync('ed25519');
  return {
    publicKey: publicKey.export({ format: 'pem', type: 'spki' }).toString(),
    privateKey: privateKey.export({ format: 'pem', type: 'pkcs8' }).toString(),
  };
}

const jwtBootstrapSecret = hex(64);
const packInstallToken = hex(32);
const backupSigningKey = base64(48);
const controlPlaneInstanceToken = hex(32);
const typesenseApiKey = hex(32);
const minioRootPassword = hex(24);
const postgresPassword = hex(24);
const defaultAdminPassword = base64(16).replace(/[+/=]/g, '').slice(0, 16);
const packKeys = generateEd25519PemPair();
const packPublicKeyJson = JSON.stringify({ default: packKeys.publicKey.trim() });

const out = `
# ===========================================================================
# Generated by scripts/generate-local-dev-secrets.ts on ${new Date().toISOString()}
# Internal-only secrets — safe to use locally. Do NOT use these values in
# production; the production deployment generates its own values via the
# secrets-manager pipeline. Append this block to .env, then fill in the
# external-service tokens (Cloudflare, HuggingFace, Anthropic, OpenAI) by
# hand.
# ===========================================================================

JWT_BOOTSTRAP_SECRET=${jwtBootstrapSecret}

DEFAULT_ADMIN_PASSWORD=${defaultAdminPassword}

DB_PASSWORD=${postgresPassword}
CONTROL_PLANE_DB_PASSWORD=${postgresPassword}
POSTGRES_PASSWORD=${postgresPassword}

MINIO_ROOT_USER=hubblewave-dev
MINIO_ROOT_PASSWORD=${minioRootPassword}

TYPESENSE_API_KEY=${typesenseApiKey}

PACK_INSTALL_TOKEN=${packInstallToken}
BACKUP_SIGNING_KEY=${backupSigningKey}
CONTROL_PLANE_INSTANCE_TOKEN=${controlPlaneInstanceToken}

PACK_SIGNING_PUBLIC_KEYS=${packPublicKeyJson}
PACK_SIGNING_PRIVATE_KEY="${packKeys.privateKey.trim()}"
`;

process.stdout.write(out);
process.stderr.write(
  '\nGenerated. Initial admin password (for first login): ' +
    defaultAdminPassword +
    '\nRotate via /users/me/change-password immediately after first login.\n'
);
