/**
 * HubbleWave Platform Setup Script
 *
 * One-command setup for development environment.
 * Handles: env files, Docker services, and database initialization.
 *
 * Usage:
 *   npx tsx scripts/setup.ts
 *   npm run setup
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import * as http from 'http';
import * as https from 'https';
import * as dotenv from 'dotenv';

const ROOT_DIR = path.resolve(__dirname, '..');

interface SetupOptions {
  skipDocker?: boolean;
  skipEnv?: boolean;
  skipAva?: boolean;
  skipSearch?: boolean;
}

function log(message: string, type: 'info' | 'success' | 'warn' | 'error' = 'info') {
  const colors = {
    info: '\x1b[36m',    // Cyan
    success: '\x1b[32m', // Green
    warn: '\x1b[33m',    // Yellow
    error: '\x1b[31m',   // Red
  };
  const reset = '\x1b[0m';
  const prefix = {
    info: '[INFO]',
    success: '[OK]',
    warn: '[WARN]',
    error: '[ERROR]',
  };
  console.log(`${colors[type]}${prefix[type]}${reset} ${message}`);
}

function generateSecret(bytes: number = 64): string {
  return crypto.randomBytes(bytes).toString('hex');
}

// Canonical set of env vars generated by this setup script.
// If an existing .env is missing any of these, it is stale and the user
// must regenerate (npm run setup:fresh) or add the missing vars manually.
const REQUIRED_ENV_VARS = [
  'JWT_KEY_PROVIDER',
  'JWT_ACCESS_TTL_SECONDS',
  'JWT_REFRESH_TTL_DAYS',
  'JWT_BOOTSTRAP_SECRET',
  'DIRECT_DB_HOST',
  'DIRECT_DB_PORT',
  'DIRECT_CONTROL_PLANE_DB_HOST',
  'DIRECT_CONTROL_PLANE_DB_PORT',
  'POSTGRES_USER',
  'POSTGRES_PASSWORD',
  'POSTGRES_DB',
  'DB_HOST',
  'DB_PORT',
  'DB_USER',
  'DB_PASSWORD',
  'DB_NAME',
  'CONTROL_PLANE_DB_HOST',
  'CONTROL_PLANE_DB_PORT',
  'CONTROL_PLANE_DB_USER',
  'CONTROL_PLANE_DB_PASSWORD',
  'CONTROL_PLANE_DB_NAME',
  'REDIS_HOST',
  'REDIS_PORT',
  'API_PORT',
  'AWS_REGION',
];

async function setupEnvFiles(): Promise<void> {
  log('Setting up environment files...');

  const envPath = path.join(ROOT_DIR, '.env');
  const envExamplePath = path.join(ROOT_DIR, '.env.example');

  if (fs.existsSync(envPath)) {
    dotenv.config({ path: envPath, override: false });
    const missing = REQUIRED_ENV_VARS.filter((v) => !process.env[v]);
    if (missing.length > 0) {
      log(`.env exists but is missing required vars: ${missing.join(', ')}`, 'warn');
      log('Your .env is from a prior setup run that predates current requirements.', 'warn');
      log('Fix: run `npm run setup:fresh` to regenerate from scratch,', 'warn');
      log('     or manually add the missing vars and re-run setup.', 'warn');
      process.exit(1);
    }
    log('.env file already exists and is current', 'success');
    return;
  }

  if (!fs.existsSync(envExamplePath)) {
    log('.env.example not found, creating default .env', 'warn');
  }

  const encryptionKey = generateSecret(32);
  const dbPassword = generateSecret(24);
  const minioPassword = generateSecret(24);
  const typesenseApiKey = generateSecret(24);
  const adminPassword = generateSecret(24);
  const adminEmail = 'admin@hubblewave.local';
  const adminFirstName = 'HubbleWave';
  const adminLastName = 'Admin';
  const adminDisplayName = `${adminFirstName} ${adminLastName}`;
  const jwtBootstrapSecret = generateSecret(32);

  const envContent = `# HubbleWave Platform Environment Configuration
# Generated by setup script on ${new Date().toISOString()}

# JWT Configuration — canon §29.9: HS256 forbidden; signing routes through KeySigningService.
# In development, JWT_KEY_PROVIDER=local-es256 uses a file-backed ES256 keypair under .dev/keys/.
# In production, set JWT_KEY_PROVIDER=aws-kms. Startup fails fast if misconfigured.
JWT_KEY_PROVIDER=local-es256
JWT_ACCESS_TTL_SECONDS=600
JWT_REFRESH_TTL_DAYS=14
# canon §29.7: dev-only service-token bootstrap secret. Production startup rejects this var.
JWT_BOOTSTRAP_SECRET=${jwtBootstrapSecret}

# Encryption Key for MFA secrets
ENCRYPTION_KEY=${encryptionKey}

# Database Configuration
DB_HOST=localhost
DB_PORT=5432
DB_USER=hubblewave
DB_PASSWORD=${dbPassword}
DB_NAME=hubblewave

# Direct DB connection (bypasses PgBouncer transaction-pooling for migrations + LISTEN/NOTIFY)
# In dev there is no PgBouncer, so these fall back to DB_HOST/DB_PORT automatically.
DIRECT_DB_HOST=localhost
DIRECT_DB_PORT=5432

# Control Plane Database
CONTROL_PLANE_DB_HOST=localhost
CONTROL_PLANE_DB_PORT=5432
CONTROL_PLANE_DB_USER=hubblewave
CONTROL_PLANE_DB_PASSWORD=${dbPassword}
CONTROL_PLANE_DB_NAME=hubblewave_control_plane

# Direct control-plane DB connection (W6.C PgBouncer; dev fallback to CONTROL_PLANE_DB_HOST/PORT)
DIRECT_CONTROL_PLANE_DB_HOST=localhost
DIRECT_CONTROL_PLANE_DB_PORT=5432

# Postgres Container Defaults
POSTGRES_USER=hubblewave
POSTGRES_PASSWORD=${dbPassword}
POSTGRES_DB=hubblewave

# Modular monolith API port (apps/api)
API_PORT=3000

# Admin Bootstrap
ADMIN_EMAIL=${adminEmail}
DEFAULT_ADMIN_PASSWORD=${adminPassword}
ADMIN_FIRST_NAME=${adminFirstName}
ADMIN_LAST_NAME=${adminLastName}
ADMIN_DISPLAY_NAME=${adminDisplayName}

# Redis Configuration
REDIS_HOST=localhost
REDIS_PORT=6379

# Storage Configuration (MinIO)
STORAGE_PROVIDER=minio
MINIO_ROOT_USER=admin
MINIO_ROOT_PASSWORD=${minioPassword}
MINIO_ENDPOINT=localhost
MINIO_PORT=9000
MINIO_USE_SSL=false
MINIO_BUCKET_ATTACHMENTS=hw-instance-attachments
MINIO_BUCKET_PACK_ARTIFACTS=hw-pack-artifacts
MINIO_BUCKET_MODEL_VAULT=hw-model-vault

# TypeSense Configuration
TYPESENSE_HOST=localhost
TYPESENSE_PORT=8108
TYPESENSE_PROTOCOL=http
TYPESENSE_API_KEY=${typesenseApiKey}

# CORS Configuration
CORS_ORIGINS=http://localhost:4200,http://localhost:5173,http://127.0.0.1:4200,http://127.0.0.1:5173
CORS_ALLOWED_HEADERS=Content-Type, Authorization, X-Requested-With, Accept, Origin

# Refresh token cookies
USE_REFRESH_TOKEN_COOKIE=true
REFRESH_COOKIE_SAMESITE=lax
REFRESH_COOKIE_PATH=/
REFRESH_COOKIE_SECURE=false

# Account lockout settings
MAX_FAILED_LOGIN_ATTEMPTS=5
ACCOUNT_LOCKOUT_DURATION_MINUTES=30

# AWS region — used by ConnectorCredentialsService (Secrets Manager) and any
# other AWS SDK client. us-east-1 is the dev default; production instances
# set this via their deployment environment.
AWS_REGION=us-east-1

# Node Environment
NODE_ENV=development

# AVA Runtime Configuration
VLLM_BASE_URL=http://localhost:11434
VLLM_DEFAULT_MODEL=llama3:latest
VLLM_EMBEDDING_MODEL=nomic-embed-text
`;

  fs.writeFileSync(envPath, envContent);
  dotenv.config({ path: envPath, override: true });
  log('.env file created with secure secrets', 'success');
}

async function checkDockerRunning(): Promise<boolean> {
  try {
    execSync('docker info', { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

async function startDockerServices(): Promise<void> {
  log('Starting Docker services...');

  if (!await checkDockerRunning()) {
    log('Docker is not running. Please start Docker Desktop and run setup again.', 'error');
    process.exit(1);
  }

  try {
    // Start services in detached mode
    execSync('docker-compose up -d', {
      cwd: ROOT_DIR,
      stdio: 'inherit',
    });
    log('Docker services started', 'success');
  } catch (error) {
    log(`Failed to start Docker services: ${error}`, 'error');
    process.exit(1);
  }
}

async function verifyPostgresCredentials(): Promise<void> {
  // After pg_isready confirms the server is accepting connections, attempt a
  // credentialed connection to catch a stale Postgres volume whose
  // superuser password doesn't match the current .env.
  const { Client } = require('pg') as typeof import('pg');
  const client = new Client({
    host: process.env.DB_HOST || 'localhost',
    port: Number(process.env.DB_PORT || 5432),
    user: process.env.DB_USER || 'hubblewave',
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME || 'hubblewave',
    connectionTimeoutMillis: 3000,
  });
  try {
    await client.connect();
    await client.end();
  } catch (err: unknown) {
    const pgErr = err as { code?: string; message?: string };
    if (pgErr.code === '28P01') {
      // password authentication failed for user
      log('', 'error');
      log('PostgreSQL rejected the credentials from .env (28P01: password mismatch).', 'error');
      log('Your Postgres volume likely has credentials from a prior setup run.', 'error');
      log('Fix: `docker-compose down -v && npm run setup`', 'error');
      log('     (The -v flag drops the data volume so Postgres reinitializes with current .env)', 'error');
      log('     Or run: npm run setup:fresh  (drops volume + deletes .env + re-runs setup)', 'error');
      process.exit(1);
    }
    if (pgErr.code === '3D000') {
      // database does not exist yet — this is fine on first run; migrations create it
      return;
    }
    // Any other connection error: log + exit so the failure is visible
    log(`Postgres credential check failed: ${pgErr.message ?? String(err)}`, 'error');
    process.exit(1);
  }
}

async function waitForPostgres(maxAttempts: number = 30): Promise<void> {
  log('Waiting for PostgreSQL to be ready...');

  for (let i = 0; i < maxAttempts; i++) {
    try {
      const dbUser = process.env.DB_USER || 'hubblewave';
      const dbName = process.env.DB_NAME || 'hubblewave';
      execSync(`docker exec hw_postgres pg_isready -U ${dbUser} -d ${dbName}`, {
        stdio: 'pipe',
      });
      log('PostgreSQL is ready', 'success');
      // Verify the credentials from .env actually work so we can surface
      // a stale-volume 28P01 error with a clear recovery hint (Issue 5).
      await verifyPostgresCredentials();
      return;
    } catch {
      process.stdout.write('.');
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  }

  log('PostgreSQL did not become ready in time', 'error');
  process.exit(1);
}

async function waitForRedis(maxAttempts: number = 30): Promise<void> {
  log('Waiting for Redis to be ready...');

  for (let i = 0; i < maxAttempts; i++) {
    try {
      execSync('docker exec hw_redis redis-cli ping', { stdio: 'pipe' });
      log('Redis is ready', 'success');
      return;
    } catch {
      process.stdout.write('.');
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  }

  log('Redis did not become ready in time', 'error');
  process.exit(1);
}

function requestStatus(url: string): Promise<number> {
  return new Promise((resolve, reject) => {
    const client = url.startsWith('https') ? https : http;
    const request = client.get(url, (response) => {
      response.resume();
      resolve(response.statusCode ?? 0);
    });
    request.on('error', reject);
    request.setTimeout(2000, () => {
      request.destroy(new Error('Request timed out'));
    });
  });
}

async function waitForHttpService(
  name: string,
  url: string,
  maxAttempts: number = 30
): Promise<void> {
  log(`Waiting for ${name} to be ready...`);

  for (let i = 0; i < maxAttempts; i++) {
    try {
      const status = await requestStatus(url);
      if (status >= 200 && status < 300) {
        log(`${name} is ready`, 'success');
        return;
      }
    } catch {
      process.stdout.write('.');
    }
    await new Promise((resolve) => setTimeout(resolve, 1000));
  }

  log(`${name} did not become ready in time`, 'error');
  process.exit(1);
}

async function runMigrations(): Promise<void> {
  log('Running database migrations...');

  try {
    execSync('npm run migration:run:control-plane', {
      cwd: ROOT_DIR,
      stdio: 'inherit',
    });
    log('Control Plane migrations completed', 'success');

    execSync('npm run migration:run:instance', {
      cwd: ROOT_DIR,
      stdio: 'inherit',
    });
    log('Instance migrations completed', 'success');
  } catch (error) {
    log(`Migration failed: ${error}`, 'error');
    process.exit(1);
  }
}

async function seedAdminUser(): Promise<void> {
  log('Seeding admin user...');

  try {
    execSync('npx tsx scripts/seed-admin-user.ts', {
      cwd: ROOT_DIR,
      stdio: 'inherit',
    });
    log('Admin user seeded', 'success');
  } catch (error) {
    log(`Failed to seed admin user: ${error}`, 'warn');
  }
}

async function bootstrapBuckets(): Promise<void> {
  log('Bootstrapping storage buckets...');

  try {
    execSync('npx tsx scripts/bootstrap-buckets.ts', {
      cwd: ROOT_DIR,
      stdio: 'inherit',
    });
    log('Buckets bootstrapped', 'success');
  } catch (error) {
    log(`Bucket bootstrap failed: ${error}`, 'error');
    process.exit(1);
  }
}

async function bootstrapTypesense(): Promise<void> {
  log('Bootstrapping TypeSense...');

  try {
    execSync('npx tsx scripts/bootstrap-typesense.ts', {
      cwd: ROOT_DIR,
      stdio: 'inherit',
    });
    log('TypeSense bootstrapped', 'success');
  } catch (error) {
    log(`TypeSense bootstrap failed: ${error}`, 'error');
    process.exit(1);
  }
}

async function seedPlatformKnowledge(): Promise<void> {
  log('Seeding platform knowledge...');

  try {
    execSync('npx tsx scripts/seed-platform-knowledge.ts', {
      cwd: ROOT_DIR,
      stdio: 'inherit',
    });
    log('Platform knowledge seeded', 'success');
  } catch (error) {
    log(`Platform knowledge seed failed: ${error}`, 'error');
    process.exit(1);
  }
}

async function installDependencies(): Promise<void> {
  log('Installing npm dependencies...');

  try {
    execSync('npm install', {
      cwd: ROOT_DIR,
      stdio: 'inherit',
    });
    log('Dependencies installed', 'success');
  } catch (error) {
    log(`Failed to install dependencies: ${error}`, 'error');
    process.exit(1);
  }
}

async function printSummary(options: SetupOptions): Promise<void> {
  const skippedLines: string[] = [];
  if (options.skipAva) {
    skippedLines.push('  - AVA Runtime (Ollama) — skipped via --skip-ava');
  }
  if (options.skipSearch) {
    skippedLines.push('  - TypeSense bootstrap — skipped via --skip-search');
  }
  const skippedBlock = skippedLines.length > 0
    ? `\nSkipped services:\n${skippedLines.join('\n')}\n`
    : '';

  console.log('\n' + '='.repeat(60));
  console.log('\x1b[32m Setup Complete! \x1b[0m');
  console.log('='.repeat(60));
  console.log(`
Services running:
  - PostgreSQL:  localhost:5432
  - Redis:       localhost:6379
  - MinIO:       localhost:9000 (Console: localhost:9001)
  - TypeSense:   localhost:8108
  - AVA Runtime: localhost:11434 (Ollama)
${skippedBlock}
Credentials:
  - Admin, database, storage, and TypeSense credentials are stored in .env
  - Admin password is printed by seed-admin-user.ts during setup

Next steps:
  1. Start the full platform (api + worker + web-client):
     npm run dev:platform

  2. Or start everything (incl. control-plane + web-control-plane):
     npm run dev:all

  3. Or start services individually:
     npm run dev:api               # Modular monolith API (port 3000)
     npm run dev:worker            # BullMQ worker
     npm run dev:web               # Web client (Vite — port printed at start)
     npm run dev:control-plane     # Control plane API
     npm run dev:web-control-plane # Control plane admin console

  4. Access the application:
     http://localhost:4200 (or whatever port Vite prints at start)
`);
  console.log('='.repeat(60) + '\n');
}

async function main(): Promise<void> {
  console.log('\n============================================================');
  console.log('  HubbleWave Platform Development Setup (Single Instance)');
  console.log('============================================================\n');

  const args = process.argv.slice(2);
  const options: SetupOptions = {
    skipDocker: args.includes('--skip-docker'),
    skipEnv: args.includes('--skip-env'),
    skipAva: args.includes('--skip-ava'),
    skipSearch: args.includes('--skip-search'),
  };

  try {
    await installDependencies();

    if (!options.skipEnv) {
      await setupEnvFiles();
    } else {
      const envPath = path.join(ROOT_DIR, '.env');
      if (fs.existsSync(envPath)) {
        dotenv.config({ path: envPath, override: false });
      }
    }

    if (!options.skipDocker) {
      await startDockerServices();
    }

    await waitForPostgres();
    await waitForRedis();
    await waitForHttpService('MinIO', 'http://localhost:9000/minio/health/live');

    if (!options.skipSearch) {
      await waitForHttpService('TypeSense', 'http://localhost:8108/health');
    } else {
      log('Skipping TypeSense wait (--skip-search)', 'warn');
    }

    if (!options.skipAva) {
      await waitForHttpService('AVA Runtime', 'http://localhost:11434/api/tags', 90);
    } else {
      log('Skipping AVA Runtime wait (--skip-ava)', 'warn');
    }

    await runMigrations();

    await bootstrapBuckets();

    if (!options.skipSearch) {
      await bootstrapTypesense();
    } else {
      log('Skipping TypeSense bootstrap (--skip-search)', 'warn');
    }

    await seedAdminUser();

    if (!options.skipAva) {
      await seedPlatformKnowledge();
    } else {
      log('Skipping platform knowledge seed (--skip-ava)', 'warn');
    }

    await printSummary(options);

  } catch (error) {
    log(`Setup failed: ${error}`, 'error');
    process.exit(1);
  }
}

main();
